// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BzAI54PM0bM64FUeOn41C_ZkxxSedZI',
    appId: '1:210975068995:web:a073849c9849fddcd215f6',
    messagingSenderId: '210975068995',
    projectId: 'simple-app-bac60',
    authDomain: 'simple-app-bac60.firebaseapp.com',
    storageBucket: 'simple-app-bac60.appspot.com',
    measurementId: 'G-FVG510BC33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vKJSKAoCHNFDCqOjE1EEEWFOiAQFyII',
    appId: '1:210975068995:android:68dbdd359f374321d215f6',
    messagingSenderId: '210975068995',
    projectId: 'simple-app-bac60',
    storageBucket: 'simple-app-bac60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdD_Sf6gXjqcbXV_ETuc2HitztRfqorwk',
    appId: '1:210975068995:ios:a3b8203dc3ee26a1d215f6',
    messagingSenderId: '210975068995',
    projectId: 'simple-app-bac60',
    storageBucket: 'simple-app-bac60.appspot.com',
    iosBundleId: 'com.example.simpleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdD_Sf6gXjqcbXV_ETuc2HitztRfqorwk',
    appId: '1:210975068995:ios:b2841bb0d45947b3d215f6',
    messagingSenderId: '210975068995',
    projectId: 'simple-app-bac60',
    storageBucket: 'simple-app-bac60.appspot.com',
    iosBundleId: 'com.example.simpleApp.RunnerTests',
  );
}
